/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteListFront {
    "front.set.cookies": [],
    "front.cp.dashboard.index": [],
    "front.cp.pages.index": [],
    "front.cp.pages.create": [],
    "front.cp.pages.edit": [
        {
            "name": "pageId",
            "required": true
        }
    ],
    "front.cp.settings.index": [],
    "front.login": [],
    "front.register": [],
    "front.page.permalink": [
        {
            "name": "permalink",
            "required": false
        }
    ],
    "verification.notice": []
}
}
export {};
