/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteListApi {
    "login": [],
    "logout": [],
    "password.email": [],
    "password.update": [],
    "register": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "sanctum.csrf-cookie": [],
    "api.user": [],
    "api.test": []
}
}
export {};
